name: Generate Changelog

on:
  workflow_dispatch: # Trigger manually from GitHub Actions
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install gitpython markdown

    - name: Generate Changelog
      run: python scripts/gen_changelog.py

    - name: Upload Changelog
      uses: actions/upload-artifact@v3
      with:
        name: changelog
        path: changelog.md
