name: Generate AI-Powered Changelog

on:
  workflow_dispatch: # Manually triggered
  push:
    branches:
      - main # Automatically trigger on main branch pushes

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install gitpython openai

    - name: Generate AI-Powered Changelog
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Securely use OpenAI API Key
      run: python scripts/generate_ai_changelog.py

    - name: Upload Changelog
      uses: actions/upload-artifact@v3
      with:
        name: changelog
        path: changelog.md
